/**
 * Generate IconName enum-like constant from iconRegistry
 *
 * This script reads the iconRegistry and generates a PascalCase enum-like
 * constant that mirrors ButtonVariant and ButtonAction patterns.
 *
 * Run: pnpm generate:icons
 */

import { writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { iconRegistry } from "../src/components/atoms/icon/icon-registry"

const __dirname = dirname(fileURLToPath(import.meta.url))

/**
 * Convert camelCase to PascalCase
 * Examples:
 *   minus -> Minus
 *   alertCircle -> AlertCircle
 *   arrowDownLeft -> ArrowDownLeft
 */
function toPascalCase(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}

function generateIconNames(): void {
  const iconKeys = Object.keys(iconRegistry).sort()

  const entries = iconKeys
    .map((key) => {
      const pascalKey = toPascalCase(key)
      return `  ${pascalKey}: "${key}"`
    })
    .join(",\n")

  const content = `/**
 * IconName - Enum-like constant for all available icons
 *
 * @generated This file is auto-generated by scripts/generate-icon-names.ts
 * Do not edit manually. Run \`pnpm generate:icons\` to regenerate.
 *
 * Usage:
 * \`\`\`tsx
 * import { IconName } from "@marwes-ui/core"
 *
 * <Icon name={IconName.AlertCircle} />
 * <Button iconRight={IconName.Minus}>Delete</Button>
 * \`\`\`
 */

export const IconName = {
${entries},
} as const

export type IconName = (typeof IconName)[keyof typeof IconName]

/**
 * Runtime list of all icon names (useful for docs, search, etc.)
 */
export const iconNamesList = Object.values(IconName)
`

  const outputPath = resolve(__dirname, "../src/components/atoms/icon/icon-names.ts")

  writeFileSync(outputPath, content, "utf-8")

  console.log(`✓ Generated ${iconKeys.length} icons to:`)
  console.log(`  ${outputPath}`)
}

generateIconNames()
